name: repub
version: 1.0.0
description: Epub Parser for Dart. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/MichaelFenwick/repub

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.1.2
  collection: ^1.15.0-nullsafety.4
  image: ^3.0.1
  quiver: ^3.0.0
  xml: ^5.0.2

dev_dependencies:
  path: ^1.8.0
  test: ^1.16.7
