name: web_ex
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Colin Nelson <colinnlsn@gmail.com>

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  repub:
    path: ../../

dev_dependencies:
  build_runner: ^2.1.0
  build_web_compilers: ^3.2.1
