name: flutter_ex
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  flutter:
    sdk: flutter

  # To get the epub from the internet
  http: ^0.13.3

  image: ^3.0.0

  # Epub
  repub:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
